# Generated by Django 5.2 on 2025-09-11 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0019_rename_profilepesonalrecord_profilepersonalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Mobilidade e Ativação Articular', [('Arm circles', 'ARM CIRCLES'), ('Leg swings', 'LEG SWINGS'), ('World’s greatest stretch', 'WORLD’S GREATEST STRETCH'), ('Inchworm to push-up', 'INCHWORM TO PUSH-UP'), ('Spiderman stretch', 'SPIDERMAN STRETCH'), ('Ankle mobility', 'ANKLE MOBILITY'), ('Hip openers', 'HIP OPENERS'), ('Scorpion stretch', 'SCORPION STRETCH'), ('Cat-cow', 'CAT-COW'), ('PVC pass-throughs', 'PVC PASS-THROUGHS')]), ('Core e Ativação de Estabilizadores', [('V-up alternado', 'V-UP ALTERNADO'), ('Hollow hold', 'HOLLOW HOLD'), ('Hollow rocks', 'HOLLOW ROCKS'), ('Arch hold', 'ARCH HOLD'), ('Dead bug', 'DEAD BUG'), ('Bird-dog', 'BIRD-DOG'), ('Glute bridge', 'GLUTE BRIDGE'), ('Side plank', 'SIDE PLANK'), ('Plank shoulder taps', 'PLANK SHOULDER TAPS')]), ('Ginástica Leve (Corpo Livre)', [('Scapular pull-up', 'SCAPULAR PULL-UP'), ('Scapular push-up', 'SCAPULAR PUSH-UP'), ('Kipping swing', 'KIPPING SWING'), ('Jumping pull-up', 'JUMPING PULL-UP'), ('Ring rows', 'RING ROWS'), ('Wall walk até a metade', 'WALL WALK ATÉ A METADE'), ('Air squat', 'AIR SQUAT'), ('Push-up', 'PUSH-UP'), ('Knee push-up', 'KNEE PUSH-UP'), ('PVC overhead squat', 'PVC OVERHEAD SQUAT')]), ('Cardio Leve / Elevação da Frequência Cardíaca', [('Jumping jacks', 'JUMPING JACKS'), ('High knees', 'HIGH KNEES'), ('Butt kicks', 'BUTT KICKS'), ('Single unders', 'SINGLE UNDERS'), ('Row 250m leve', 'ROW 250M LEVE'), ('Assault bike 1-2 min', 'ASSAULT BIKE 1-2 MIN'), ('Jogging no lugar', 'JOGGING NO LUGAR')]), ('Movimentos Técnicos com Carga Leve', [('Empty barbell good mornings', 'EMPTY BARBELL GOOD MORNINGS'), ('Barbell deadlifts com barra vazia', 'BARBELL DEADLIFTS COM BARRA VAZIA'), ('Barbell front squats', 'BARBELL FRONT SQUATS'), ('Barbell overhead squats', 'BARBELL OVERHEAD SQUATS'), ('Barbell presses', 'BARBELL PRESSES'), ('Snatch balance com PVC', 'SNATCH BALANCE COM PVC'), ('Burgener warm-up', 'BURGENER WARM-UP')]), ('BARBELL', [('back squat', 'BACK SQUAT'), ('bench press', 'BENCH PRESS'), ('clean', 'CLEAN'), ('clean & jerk', 'CLEAN & JERK'), ('clean pull', 'CLEAN PULL'), ('cluster', 'CLUSTER'), ('deadlift', 'DEADLIFT'), ('deadlift fat bar', 'DEADLIFT FAT BAR'), ('front squat', 'FRONT SQUAT'), ('hang clean', 'HANG CLEAN'), ('hang power clean', 'HANG POWER CLEAN'), ('hang power snatch', 'HANG POWER SNATCH'), ('hang snatch', 'HANG SNATCH'), ('muscle clean', 'MUSCLE CLEAN'), ('muscle snatch', 'MUSCLE SNATCH'), ('overhead lunge', 'OVERHEAD LUNGE'), ('overhead squat', 'OVERHEAD SQUAT'), ('power clean', 'POWER CLEAN'), ('push jerk', 'PUSH JERK'), ('push press', 'PUSH PRESS'), ('shoulder press', 'SHOULDER PRESS'), ('snatch', 'SNATCH'), ('snatch deadlift', 'SNATCH DEADLIFT'), ('snatch pull', 'SNATCH PULL'), ('split jerk', 'SPLIT JERK'), ('squat clean', 'SQUAT CLEAN'), ('squat jerk', 'SQUAT JERK'), ('squat snatch', 'SQUAT SNATCH'), ('squat deadlift', 'SQUAT DEADLIFT'), ('sumo deadlift', 'SUMO DEADLIFT'), ('sumo deadlift high pull', 'SUMO DEADLIFT HIGH PULL'), ('thruster', 'THRUSTER')]), ('ENDURANCE', [('air bike', 'AIR BIKE'), ('max burpee', 'MAX BURPEE'), ('max sit up', 'MAX SIT UP'), ('max squat', 'MAX SQUAT'), ('row', 'ROW'), ('run', 'RUN')]), ('GYMNASTIC', [('abmat sit-up', 'ABMAT SIT-UP'), ('box jump', 'BOX JUMP'), ('double-under', 'DOUBLE-UNDER'), ('handstand push-up', 'HANDSTAND PUSH-UP'), ('handstand walk', 'HANDSTAND WALK'), ('l-sit', 'L-SIT'), ('muscle-up', 'MUSCLE-UP'), ('pull-up(strict)', 'PULL-UP(STRICT)'), ('pull-up(weighted)', 'PULL-UP(WEIGHTED)'), ('pushup', 'PUSHUP'), ('ring dip', 'RING DIP'), ('rope climb', 'ROPE CLIMB'), ('toes to bar', 'TOES TO BAR'), ('wall ball', 'WALL BALL')])], max_length=50)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Warmup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_warmup', models.CharField(blank=True, choices=[('Mobilidade e Ativação Articular', [('Arm circles', 'ARM CIRCLES'), ('Leg swings', 'LEG SWINGS'), ('World’s greatest stretch', 'WORLD’S GREATEST STRETCH'), ('Inchworm to push-up', 'INCHWORM TO PUSH-UP'), ('Spiderman stretch', 'SPIDERMAN STRETCH'), ('Ankle mobility', 'ANKLE MOBILITY'), ('Hip openers', 'HIP OPENERS'), ('Scorpion stretch', 'SCORPION STRETCH'), ('Cat-cow', 'CAT-COW'), ('PVC pass-throughs', 'PVC PASS-THROUGHS')]), ('Core e Ativação de Estabilizadores', [('V-up alternado', 'V-UP ALTERNADO'), ('Hollow hold', 'HOLLOW HOLD'), ('Hollow rocks', 'HOLLOW ROCKS'), ('Arch hold', 'ARCH HOLD'), ('Dead bug', 'DEAD BUG'), ('Bird-dog', 'BIRD-DOG'), ('Glute bridge', 'GLUTE BRIDGE'), ('Side plank', 'SIDE PLANK'), ('Plank shoulder taps', 'PLANK SHOULDER TAPS')]), ('Ginástica Leve (Corpo Livre)', [('Scapular pull-up', 'SCAPULAR PULL-UP'), ('Scapular push-up', 'SCAPULAR PUSH-UP'), ('Kipping swing', 'KIPPING SWING'), ('Jumping pull-up', 'JUMPING PULL-UP'), ('Ring rows', 'RING ROWS'), ('Wall walk até a metade', 'WALL WALK ATÉ A METADE'), ('Air squat', 'AIR SQUAT'), ('Push-up', 'PUSH-UP'), ('Knee push-up', 'KNEE PUSH-UP'), ('PVC overhead squat', 'PVC OVERHEAD SQUAT')]), ('Cardio Leve / Elevação da Frequência Cardíaca', [('Jumping jacks', 'JUMPING JACKS'), ('High knees', 'HIGH KNEES'), ('Butt kicks', 'BUTT KICKS'), ('Single unders', 'SINGLE UNDERS'), ('Row 250m leve', 'ROW 250M LEVE'), ('Assault bike 1-2 min', 'ASSAULT BIKE 1-2 MIN'), ('Jogging no lugar', 'JOGGING NO LUGAR')]), ('Movimentos Técnicos com Carga Leve', [('Empty barbell good mornings', 'EMPTY BARBELL GOOD MORNINGS'), ('Barbell deadlifts com barra vazia', 'BARBELL DEADLIFTS COM BARRA VAZIA'), ('Barbell front squats', 'BARBELL FRONT SQUATS'), ('Barbell overhead squats', 'BARBELL OVERHEAD SQUATS'), ('Barbell presses', 'BARBELL PRESSES'), ('Snatch balance com PVC', 'SNATCH BALANCE COM PVC'), ('Burgener warm-up', 'BURGENER WARM-UP')]), ('BARBELL', [('back squat', 'BACK SQUAT'), ('bench press', 'BENCH PRESS'), ('clean', 'CLEAN'), ('clean & jerk', 'CLEAN & JERK'), ('clean pull', 'CLEAN PULL'), ('cluster', 'CLUSTER'), ('deadlift', 'DEADLIFT'), ('deadlift fat bar', 'DEADLIFT FAT BAR'), ('front squat', 'FRONT SQUAT'), ('hang clean', 'HANG CLEAN'), ('hang power clean', 'HANG POWER CLEAN'), ('hang power snatch', 'HANG POWER SNATCH'), ('hang snatch', 'HANG SNATCH'), ('muscle clean', 'MUSCLE CLEAN'), ('muscle snatch', 'MUSCLE SNATCH'), ('overhead lunge', 'OVERHEAD LUNGE'), ('overhead squat', 'OVERHEAD SQUAT'), ('power clean', 'POWER CLEAN'), ('push jerk', 'PUSH JERK'), ('push press', 'PUSH PRESS'), ('shoulder press', 'SHOULDER PRESS'), ('snatch', 'SNATCH'), ('snatch deadlift', 'SNATCH DEADLIFT'), ('snatch pull', 'SNATCH PULL'), ('split jerk', 'SPLIT JERK'), ('squat clean', 'SQUAT CLEAN'), ('squat jerk', 'SQUAT JERK'), ('squat snatch', 'SQUAT SNATCH'), ('squat deadlift', 'SQUAT DEADLIFT'), ('sumo deadlift', 'SUMO DEADLIFT'), ('sumo deadlift high pull', 'SUMO DEADLIFT HIGH PULL'), ('thruster', 'THRUSTER')]), ('ENDURANCE', [('air bike', 'AIR BIKE'), ('max burpee', 'MAX BURPEE'), ('max sit up', 'MAX SIT UP'), ('max squat', 'MAX SQUAT'), ('row', 'ROW'), ('run', 'RUN')]), ('GYMNASTIC', [('abmat sit-up', 'ABMAT SIT-UP'), ('box jump', 'BOX JUMP'), ('double-under', 'DOUBLE-UNDER'), ('handstand push-up', 'HANDSTAND PUSH-UP'), ('handstand walk', 'HANDSTAND WALK'), ('l-sit', 'L-SIT'), ('muscle-up', 'MUSCLE-UP'), ('pull-up(strict)', 'PULL-UP(STRICT)'), ('pull-up(weighted)', 'PULL-UP(WEIGHTED)'), ('pushup', 'PUSHUP'), ('ring dip', 'RING DIP'), ('rope climb', 'ROPE CLIMB'), ('toes to bar', 'TOES TO BAR'), ('wall ball', 'WALL BALL')])], max_length=200, null=True)),
                ('time_warmup', models.FloatField()),
                ('rep_movement', models.IntegerField(blank=True, null=True)),
                ('text_warmup', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time', models.CharField(choices=[('amrap', 'AMRAP'), ('emom', 'EMOM'), ('tabata', 'TABATA'), ('rft ', 'RFT '), ('rnft', 'RNFT '), ('rx', 'RX '), ('rm', 'RM '), ('rm', 'RM '), ('rm', 'RM ')], default='00:00', max_length=50)),
                ('description_wod', models.TextField(max_length=2000)),
                ('pinned', models.BooleanField(default=False)),
                ('elite', models.IntegerField(default=0)),
                ('rx', models.IntegerField(default=0)),
                ('amauter', models.IntegerField(default=0)),
                ('scaled', models.IntegerField(default=0)),
                ('fit', models.IntegerField(default=0)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_skill', models.CharField(blank=True, choices=[('Mobilidade e Ativação Articular', [('Arm circles', 'ARM CIRCLES'), ('Leg swings', 'LEG SWINGS'), ('World’s greatest stretch', 'WORLD’S GREATEST STRETCH'), ('Inchworm to push-up', 'INCHWORM TO PUSH-UP'), ('Spiderman stretch', 'SPIDERMAN STRETCH'), ('Ankle mobility', 'ANKLE MOBILITY'), ('Hip openers', 'HIP OPENERS'), ('Scorpion stretch', 'SCORPION STRETCH'), ('Cat-cow', 'CAT-COW'), ('PVC pass-throughs', 'PVC PASS-THROUGHS')]), ('Core e Ativação de Estabilizadores', [('V-up alternado', 'V-UP ALTERNADO'), ('Hollow hold', 'HOLLOW HOLD'), ('Hollow rocks', 'HOLLOW ROCKS'), ('Arch hold', 'ARCH HOLD'), ('Dead bug', 'DEAD BUG'), ('Bird-dog', 'BIRD-DOG'), ('Glute bridge', 'GLUTE BRIDGE'), ('Side plank', 'SIDE PLANK'), ('Plank shoulder taps', 'PLANK SHOULDER TAPS')]), ('Ginástica Leve (Corpo Livre)', [('Scapular pull-up', 'SCAPULAR PULL-UP'), ('Scapular push-up', 'SCAPULAR PUSH-UP'), ('Kipping swing', 'KIPPING SWING'), ('Jumping pull-up', 'JUMPING PULL-UP'), ('Ring rows', 'RING ROWS'), ('Wall walk até a metade', 'WALL WALK ATÉ A METADE'), ('Air squat', 'AIR SQUAT'), ('Push-up', 'PUSH-UP'), ('Knee push-up', 'KNEE PUSH-UP'), ('PVC overhead squat', 'PVC OVERHEAD SQUAT')]), ('Cardio Leve / Elevação da Frequência Cardíaca', [('Jumping jacks', 'JUMPING JACKS'), ('High knees', 'HIGH KNEES'), ('Butt kicks', 'BUTT KICKS'), ('Single unders', 'SINGLE UNDERS'), ('Row 250m leve', 'ROW 250M LEVE'), ('Assault bike 1-2 min', 'ASSAULT BIKE 1-2 MIN'), ('Jogging no lugar', 'JOGGING NO LUGAR')]), ('Movimentos Técnicos com Carga Leve', [('Empty barbell good mornings', 'EMPTY BARBELL GOOD MORNINGS'), ('Barbell deadlifts com barra vazia', 'BARBELL DEADLIFTS COM BARRA VAZIA'), ('Barbell front squats', 'BARBELL FRONT SQUATS'), ('Barbell overhead squats', 'BARBELL OVERHEAD SQUATS'), ('Barbell presses', 'BARBELL PRESSES'), ('Snatch balance com PVC', 'SNATCH BALANCE COM PVC'), ('Burgener warm-up', 'BURGENER WARM-UP')]), ('BARBELL', [('back squat', 'BACK SQUAT'), ('bench press', 'BENCH PRESS'), ('clean', 'CLEAN'), ('clean & jerk', 'CLEAN & JERK'), ('clean pull', 'CLEAN PULL'), ('cluster', 'CLUSTER'), ('deadlift', 'DEADLIFT'), ('deadlift fat bar', 'DEADLIFT FAT BAR'), ('front squat', 'FRONT SQUAT'), ('hang clean', 'HANG CLEAN'), ('hang power clean', 'HANG POWER CLEAN'), ('hang power snatch', 'HANG POWER SNATCH'), ('hang snatch', 'HANG SNATCH'), ('muscle clean', 'MUSCLE CLEAN'), ('muscle snatch', 'MUSCLE SNATCH'), ('overhead lunge', 'OVERHEAD LUNGE'), ('overhead squat', 'OVERHEAD SQUAT'), ('power clean', 'POWER CLEAN'), ('push jerk', 'PUSH JERK'), ('push press', 'PUSH PRESS'), ('shoulder press', 'SHOULDER PRESS'), ('snatch', 'SNATCH'), ('snatch deadlift', 'SNATCH DEADLIFT'), ('snatch pull', 'SNATCH PULL'), ('split jerk', 'SPLIT JERK'), ('squat clean', 'SQUAT CLEAN'), ('squat jerk', 'SQUAT JERK'), ('squat snatch', 'SQUAT SNATCH'), ('squat deadlift', 'SQUAT DEADLIFT'), ('sumo deadlift', 'SUMO DEADLIFT'), ('sumo deadlift high pull', 'SUMO DEADLIFT HIGH PULL'), ('thruster', 'THRUSTER')]), ('ENDURANCE', [('air bike', 'AIR BIKE'), ('max burpee', 'MAX BURPEE'), ('max sit up', 'MAX SIT UP'), ('max squat', 'MAX SQUAT'), ('row', 'ROW'), ('run', 'RUN')]), ('GYMNASTIC', [('abmat sit-up', 'ABMAT SIT-UP'), ('box jump', 'BOX JUMP'), ('double-under', 'DOUBLE-UNDER'), ('handstand push-up', 'HANDSTAND PUSH-UP'), ('handstand walk', 'HANDSTAND WALK'), ('l-sit', 'L-SIT'), ('muscle-up', 'MUSCLE-UP'), ('pull-up(strict)', 'PULL-UP(STRICT)'), ('pull-up(weighted)', 'PULL-UP(WEIGHTED)'), ('pushup', 'PUSHUP'), ('ring dip', 'RING DIP'), ('rope climb', 'ROPE CLIMB'), ('toes to bar', 'TOES TO BAR'), ('wall ball', 'WALL BALL')])], null=True)),
                ('time_skill', models.CharField(choices=[('amrap', 'AMRAP'), ('emom', 'EMOM'), ('tabata', 'TABATA'), ('rft ', 'RFT '), ('rnft', 'RNFT '), ('rx', 'RX '), ('rm', 'RM '), ('rm', 'RM '), ('rm', 'RM ')], default='00:00')),
                ('rep_skill', models.IntegerField(blank=True, null=True)),
                ('weight_skill', models.FloatField(blank=True, null=True)),
                ('round_skill', models.IntegerField(blank=True, null=True)),
                ('text_skill', models.TextField(blank=True, null=True)),
                ('wod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WOD.wod')),
            ],
        ),
        migrations.CreateModel(
            name='WodTraning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep', models.PositiveBigIntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('distance', models.CharField(max_length=50)),
                ('round', models.IntegerField(default=0)),
                ('ord', models.PositiveIntegerField(default=1)),
                ('obs', models.TextField(max_length=2000)),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WOD.movement')),
                ('wod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicio', to='WOD.wod')),
            ],
            options={
                'ordering': ['ord'],
            },
        ),
    ]
