# Generated by Django 5.2 on 2025-09-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='wod',
        ),
        migrations.DeleteModel(
            name='Warmup',
        ),
        migrations.RemoveField(
            model_name='wodtraning',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='wodtraning',
            name='wod',
        ),
        migrations.RemoveField(
            model_name='wod',
            name='time',
        ),
        migrations.AlterField(
            model_name='wod',
            name='description_wod',
            field=models.TextField(max_length=10000),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='WodTraning',
        ),
    ]
