# Generated by Django 5.2 on 2025-09-27 01:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOD', '0002_remove_skill_wod_delete_warmup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wod',
            name='like',
            field=models.ManyToManyField(related_name='liked_wod', to=settings.AUTH_USER_MODEL),
        ),
    ]
