# Generated by Django 5.2 on 2025-09-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOD', '0003_wod_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='wod',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default='2025-09-28 14:00:00'),
            preserve_default=False,
        ),
    ]
