# Generated by Django 5.2 on 2025-09-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOD', '0004_wod_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wod',
            name='created_at',
        ),
        migrations.AddField(
            model_name='wod',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2025-09-28 14:00:00'),
            preserve_default=False,
        ),
    ]
