# Generated by Django 5.2 on 2025-05-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_birthday_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
