# Generated by Django 5.2 on 2025-05-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at_profile',
            field=models.DateField(auto_now=True),
        ),
    ]
