# Generated by Django 5.2 on 2025-07-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('FITNESS', 'FITNESS'), ('SCALED', 'SCALED'), ('AMADOR', 'AMADOR'), ('RX', 'RX'), ('MASTER', 'MASTER')], default='EXPERIMENTAL'),
        ),
    ]
