# Generated by Django 5.2 on 2025-07-17 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='box',
            field=models.CharField(choices=[('CF4TIME CAMPINA ', 'CF4TIME CAMPINA'), ('CF4TIME CAMPINA', 'CF4TIME JOCKEY')], default='DEFAULT'),
        ),
    ]
