# Generated by Django 5.2 on 2025-07-18 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_profile_weight_alter_profile_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
    ]
