# Generated by Django 5.2 on 2025-07-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_coach',
            field=models.BooleanField(default=False),
        ),
    ]
