# Generated by Django 5.2 on 2025-08-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_profile_is_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='genre',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO'), ('NÃO-ESPECIFICAR', 'NÃO-ESPECIFICAR')], default='NÃO-ESPECIFICAR'),
        ),
    ]
