# Generated by Django 5.2 on 2025-08-13 02:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_profile_height_profilepesonalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepesonalrecord',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profilepesonalrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, max_length=50),
        ),
        migrations.AddField(
            model_name='profilepesonalrecord',
            name='moviment',
            field=models.CharField(choices=[('BACK SQUAT', 'BACK SQUAT'), ('BENCH PRESS', 'BENCH PRESS')], default='NONE'),
        ),
    ]
