# Generated by Django 5.2 on 2025-08-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_profilepesonalrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='view_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_height',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_weight',
            field=models.BooleanField(default=False),
        ),
    ]
