# Generated by Django 5.2 on 2025-08-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_profile_view_box_profile_view_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='view_box',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='view_category',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='view_height',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='view_weight',
            field=models.BooleanField(default=True),
        ),
    ]
