# Generated by Django 5.2 on 2025-08-21 20:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_profile_view_box_alter_profile_view_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePesonalRecord',
            new_name='ProfilePersonalRecord',
        ),
    ]
