# Generated by Django 5.2 on 2025-09-28 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOD', '0005_remove_wod_created_at_wod_date'),
        ('account', '0019_rename_profilepesonalrecord_profilepersonalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonalrecord',
            name='moviment',
            field=models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.CASCADE, to='WOD.movement'),
        ),
    ]
