# Generated by Django 5.2 on 2025-09-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_profilepersonalrecord_moviment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepersonalrecord',
            name='view_personal_record',
            field=models.BooleanField(default=True),
        ),
    ]
