# Generated by Django 5.2 on 2025-09-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_profilepersonalrecord_view_personal_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepersonalrecord',
            name='view_personal_record',
        ),
        migrations.AddField(
            model_name='profile',
            name='view_personal_record',
            field=models.BooleanField(default=True),
        ),
    ]
