release: python manage.py migrate && python manage.py collectstatic --noinput && python manage.py createsuperuser --noinput || true
web: gunicorn app.wsgi --log-file -
worker: celery -A app worker --loglevel=info --concurrency=2 --max-tasks-per-child=10
beat: celery -A app beat --loglevel=info

