# Generated by Django 5.2 on 2025-08-07 02:26

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Event', '0002_delete_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(default='null', max_length=50)),
                ('title', models.CharField(default='null', max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('date_initial', models.DateField(default=datetime.datetime(2025, 8, 7, 2, 26, 34, 804358, tzinfo=datetime.timezone.utc))),
                ('date_end', models.DateField(default=datetime.datetime(2025, 8, 7, 2, 26, 34, 804358, tzinfo=datetime.timezone.utc))),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
