# Generated by Django 5.2 on 2025-08-13 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0008_alter_event_date_end_alter_event_date_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2025, 8, 13, 3, 43, 37, 196661, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_initial',
            field=models.DateField(default=datetime.datetime(2025, 8, 13, 3, 43, 37, 196661, tzinfo=datetime.timezone.utc)),
        ),
    ]
