# Generated by Django 5.2 on 2025-08-15 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0009_alter_event_date_end_alter_event_date_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2025, 8, 15, 0, 4, 31, 980782, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_initial',
            field=models.DateField(default=datetime.datetime(2025, 8, 15, 0, 4, 31, 980782, tzinfo=datetime.timezone.utc)),
        ),
    ]
