# Generated by Django 5.2 on 2025-08-21 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0012_alter_event_date_end_alter_event_date_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2025, 8, 21, 20, 35, 56, 852908, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_initial',
            field=models.DateField(default=datetime.datetime(2025, 8, 21, 20, 35, 56, 852908, tzinfo=datetime.timezone.utc)),
        ),
    ]
