# Generated by Django 5.2 on 2025-08-22 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0013_alter_event_date_end_alter_event_date_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2025, 8, 22, 0, 15, 22, 833738, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_initial',
            field=models.DateField(default=datetime.datetime(2025, 8, 22, 0, 15, 22, 833738, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
