# Generated by Django 5.2 on 2025-08-27 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0014_alter_event_date_end_alter_event_date_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2025, 8, 27, 22, 27, 8, 627055, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_initial',
            field=models.DateField(default=datetime.datetime(2025, 8, 27, 22, 27, 8, 627055, tzinfo=datetime.timezone.utc)),
        ),
    ]
