# Generated by Django 5.2 on 2025-09-05 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0020_alter_event_date_end_alter_event_date_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2025, 9, 5, 2, 31, 20, 929007, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_initial',
            field=models.DateField(default=datetime.datetime(2025, 9, 5, 2, 31, 20, 928992, tzinfo=datetime.timezone.utc)),
        ),
    ]
