# Generated by Django 5.2 on 2025-09-09 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0025_alter_event_date_end_alter_event_date_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2025, 9, 9, 0, 23, 42, 658099, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_initial',
            field=models.DateField(default=datetime.datetime(2025, 9, 9, 0, 23, 42, 658084, tzinfo=datetime.timezone.utc)),
        ),
    ]
