# Generated by Django 5.2 on 2025-09-11 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0046_alter_event_date_end_alter_event_date_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 11, 2, 3, 46, 709759, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_initial',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 11, 2, 3, 46, 709744, tzinfo=datetime.timezone.utc)),
        ),
    ]
