# Generated by Django 5.2 on 2025-10-05 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0066_alter_event_date_end_alter_event_date_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 5, 23, 22, 44, 653062, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_initial',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 5, 23, 22, 44, 653046, tzinfo=datetime.timezone.utc)),
        ),
    ]
