# Generated by Django 5.2 on 2025-04-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0002_post_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
