# Generated by Django 5.2 on 2025-04-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0003_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
