# Generated by Django 5.2 on 2025-04-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0005_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
