# Generated by Django 5.2 on 2025-04-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0008_alter_post_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='usuario',
            new_name='author',
        ),
    ]
