# Generated by Django 5.2 on 2025-05-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0018_alter_postcommentinventory_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcommentinventory',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postcommentinventory',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
