# Generated by Django 5.2 on 2025-06-20 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0022_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
