# Generated by Django 5.2 on 2025-06-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0023_remove_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(blank=True, db_default=0, null=True),
        ),
    ]
