# Generated by Django 5.2 on 2025-06-20 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0026_alter_post_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_comment',
            field=models.ManyToManyField(related_name='liked_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
