# Generated by Django 5.2 on 2025-07-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0027_comment_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media_poost'),
        ),
    ]
