# Generated by Django 5.2 on 2025-07-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0028_post_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='document',
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media_post'),
        ),
    ]
