# Generated by Django 5.2 on 2025-07-19 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0029_remove_post_document_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
