# Generated by Django 5.2 on 2025-07-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0030_remove_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media_post'),
        ),
    ]
