# Generated by Django 5.2 on 2025-07-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0032_remove_post_photo_remove_post_video_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media_post'),
        ),
    ]
