# Generated by Django 5.2 on 2025-07-31 00:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0035_posttreino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostTreino',
            new_name='PostWod',
        ),
    ]
