# Generated by Django 5.2 on 2025-07-31 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0036_rename_posttreino_postwod'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='post_coach',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='Social.postwod'),
        ),
    ]
