# Generated by Django 5.2 on 2025-07-31 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0037_postimage_post_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvideo',
            name='post_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_videos', to='Social.postwod'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Social.post'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_images', to='Social.postwod'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Social.post'),
        ),
    ]
