# Generated by Django 5.2 on 2025-07-31 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0038_postvideo_post_coach_alter_postimage_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post_coach',
        ),
        migrations.RemoveField(
            model_name='postvideo',
            name='post_coach',
        ),
    ]
