# Generated by Django 5.2 on 2025-07-31 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0039_remove_postimage_post_coach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postwod',
            name='skill',
            field=models.CharField(default='NONE', max_length=255),
        ),
        migrations.AddField(
            model_name='postwod',
            name='warmup',
            field=models.CharField(default='NONE', max_length=255),
        ),
        migrations.AlterField(
            model_name='postwod',
            name='title',
            field=models.CharField(default='NONE', max_length=255),
        ),
    ]
