# Generated by Django 5.2 on 2025-07-31 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0040_postwod_skill_postwod_warmup_alter_postwod_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='postwod',
            name='post',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Social.post'),
            preserve_default=False,
        ),
    ]
