# Generated by Django 5.2 on 2025-07-31 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0041_postwod_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postwod',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Social.post'),
        ),
    ]
