# Generated by Django 5.2 on 2025-07-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0043_alter_postwod_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postwod',
            name='post',
        ),
        migrations.AddField(
            model_name='postwod',
            name='text',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
