# Generated by Django 5.2 on 2025-08-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0044_remove_postwod_post_postwod_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postwod',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
