# Generated by Django 5.2 on 2025-08-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0045_alter_postwod_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='postwod',
            name='text',
            field=models.CharField(max_length=3000),
        ),
    ]
