# Generated by Django 5.2 on 2025-09-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0047_story_storymedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storymedia',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='storymedia',
            name='video',
        ),
        migrations.AddField(
            model_name='storymedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/media_story_file'),
        ),
    ]
