# Generated by Django 5.2 on 2025-09-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0048_remove_storymedia_photo_remove_storymedia_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storymedia',
            name='file',
        ),
        migrations.AddField(
            model_name='storymedia',
            name='document',
            field=models.FileField(blank=True, default='none', null=True, upload_to='media/media_story_file'),
        ),
    ]
