# Generated by Django 5.2 on 2025-09-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0049_remove_storymedia_file_storymedia_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymedia',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/media_story_file'),
        ),
    ]
