# Generated by Django 5.2 on 2025-09-08 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0050_alter_storymedia_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostWod',
        ),
    ]
