# Generated by Django 5.2 on 2025-10-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0051_delete_postwod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymedia',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media_story'),
        ),
    ]
