# Generated by Django 5.2 on 2025-10-04 23:39

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0052_alter_storymedia_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage, upload_to='media_post'),
        ),
        migrations.AlterField(
            model_name='storymedia',
            name='document',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='media_story'),
        ),
    ]
