# Generated by Django 5.2 on 2025-10-07 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0054_storyimage_storyvideo_delete_storymedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyvideo',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_videos', to='Social.story'),
        ),
    ]
